  spring:
    cloud:
      gateway:
        routes:
          - id: patient-service-route
            uri: http://patient-service:8081/
            predicates:
              - Path=/patientService/**
            filters:
              - RewritePath=/patientService/(?<segment>.*), /$\{segment}

          - id: history-service-route
            uri: http://history-service:8082/
            predicates:
              - Path=/historyService/**
            filters:
              - RewritePath=/historyService/(?<segment>.*), /$\{segment}

          - id: assessment-service-route
            uri: http://assessment-service:8080/
            predicates:
              - Path=/assessService/**
            filters:
              - RewritePath=/assessService/(?<segment>.*), /$\{segment}

          - id: users-service-route
            uri: http://user-service:8083/
            predicates:
              - Path=/usersService/**
            filters:
              - RewritePath=/usersService/(?<segment>.*), /$\{segment}